### ISSUE TITLE
Not parsed obsolete entries

### ISSUE THREAD

**Issue by ekaragodin** [geekwright/Po#1]
PoFile returns empty array of entries.

```
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2015-06-08 07:31+0000\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language: ru_RU\n"

#~ msgid "year"
#~ msgstr "год"

```

**Comment by geekwright** [comment]
Thanks for the report. I'm unfortunately insanely busy for the next two weeks, but I'll dig in to it as soon as I can.

**Comment by geekwright** [comment]
Actually, the obsolete entries are parsed and stored. But, since the entries are all technically comments, there is no key (msgid, msgstr, msgctxt, etc.) to refer to them. The obsolete entries are stored in the $unkeyedEntries property in PoFile. Here is a simple example of accessing an array of  obsolete entries:

``` PHP
    $poFile = new PoFile();
    $poFile->readPoFile($file);

    $unKeyedEntries = $poFile->getUnkeyedEntries();
    $obsoleteEntries = array();
    foreach ($unKeyedEntries as $entry) {
        $obs = $entry->get(PoTokens::OBSOLETE);
        if ($obs !== null) {
            $obsoleteEntries[] = $obs;
        }
    }
    var_dump($obsoleteEntries);
```

These entries should follow along through a PoFile::readPoFile() to PoFile::writePoFile() cycle. However, since there is no guarantee that they will meaningful or unique in any given circumstance, they are left as special comments, and not included in the regular "keyed" entries.

If you can propose a better way to handle them, I would be open to considering it.
